# Generated by Django 4.2.3 on 2023-08-01 06:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("collect", "0003_rename_full_data_allprobability_data_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="data",
            name="storeName",
            field=models.CharField(default="0", max_length=100),
        ),
    ]
