# Generated by Django 4.2.3 on 2023-08-16 03:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("collect", "0004_data_storename"),
    ]

    operations = [
        migrations.CreateModel(
            name="standard_data",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("level", models.IntegerField(default=0)),
                ("modelName", models.CharField(max_length=100)),
                ("allprobability", models.FloatField(default=0.0)),
                ("BBprobability", models.FloatField(default=0.0)),
                ("RBprobability", models.FloatField(default=0.0)),
            ],
        ),
    ]
