# Generated by Django 4.2.3 on 2023-08-29 03:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("collect", "0005_standard_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="data",
            name="setting",
            field=models.IntegerField(default=0),
        ),
    ]
